# Generated by Django 5.0.14 on 2026-09-01 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('regular_price', models.FloatField()),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=700)),
                ('stock_status', models.CharField(default='instock', max_length=40)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('max_quantity_per_order', models.IntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('warehouse', models.CharField(choices=[('WAREHOUSE_1', 'Warehouse 1'), ('WAREHOUSE_2', 'Warehouse 2')], default='WAREHOUSE_2', max_length=20)),
                ('status', models.CharField(default='publish', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=160)),
                ('image_path', models.CharField(max_length=700)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='catalog.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='catalog.product')),
            ],
            options={
                'unique_together': {('product', 'category')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', through='catalog.ProductCategory', to='catalog.category'),
        ),
    ]
