# Generated by Django 5.0.14 on 2026-09-01 19:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=700)),
                ('href', models.CharField(blank=True, max_length=300)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=160)),
                ('question', models.CharField(max_length=400)),
                ('answer', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ item',
                'ordering': ['sort_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='cms/')),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('href', models.CharField(max_length=300)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer_products', 'Footer · Products'), ('footer_company', 'Footer · Company'), ('footer_resources', 'Footer · Resources'), ('footer_policies', 'Footer · Policies')], max_length=40)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['location', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('lede', models.TextField(blank=True)),
                ('body', models.TextField(help_text='HTML allowed. Shown on the storefront.')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('group', models.CharField(default='general', max_length=40)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
    ]
