from django.urls import path

from cms import bulk_email_views, ops_views, views

urlpatterns = [
    path("cms/pages/", views.public_pages),
    path("cms/banners/", views.public_banners),
    path("cms/faq/", views.public_faq),
    path("cms/nav/", views.public_nav),
    path("cms/settings/", views.public_settings),
    path("cms/warehouse-policy/", views.public_warehouse_policy),
    path("admin/cms/pages/", views.admin_pages),
    path("admin/cms/pages/<uuid:pk>/", views.admin_page_detail),
    path("admin/cms/banners/visibility/", views.admin_banner_visibility),
    path("admin/cms/banners/display-mode/", views.admin_banner_display_mode),
    path("admin/cms/banners/", views.admin_banners),
    path("admin/cms/banners/<uuid:pk>/restore/", views.admin_banner_restore),
    path("admin/cms/banners/<uuid:pk>/", views.admin_banner_detail),
    path("admin/cms/faq/", views.admin_faq),
    path("admin/cms/faq/<uuid:pk>/", views.admin_faq_detail),
    path("admin/cms/nav/", views.admin_nav),
    path("admin/cms/nav/<uuid:pk>/", views.admin_nav_detail),
    path("admin/cms/settings/", views.admin_settings),
    path("admin/cms/email-settings/", views.admin_email_settings),
    path("admin/cms/email-templates/", views.admin_email_templates),
    path("admin/cms/email-templates/<uuid:pk>/", views.admin_email_template_detail),
    path("admin/cms/email-test/", views.admin_email_test),
    path("admin/cms/warehouse-settings/", views.admin_warehouse_settings),
    path("admin/dashboard/tiles/", ops_views.admin_dashboard_tiles_view),
    path("admin/ops-settings/", ops_views.admin_ops_settings_view),
    path("checkout-settings/", ops_views.public_checkout_settings_view),
    path("admin/email/bulk/template/", bulk_email_views.bulk_template_view),
    path("admin/email/bulk/preview/", bulk_email_views.bulk_preview_view),
    path("admin/email/bulk/render-preview/", bulk_email_views.bulk_render_preview_view),
    path("admin/email/bulk/send/", bulk_email_views.bulk_send_view),
    path("admin/email/bulk/batches/", bulk_email_views.bulk_batch_list_view),
    path("admin/email/bulk/batches/<uuid:pk>/", bulk_email_views.bulk_batch_detail_view),
    path("admin/email/bulk/batches/<uuid:pk>/recipients/", bulk_email_views.bulk_batch_recipients_view),
    path("admin/email/bulk/batches/<uuid:pk>/pause/", bulk_email_views.bulk_batch_pause_view),
    path("admin/email/bulk/batches/<uuid:pk>/stop/", bulk_email_views.bulk_batch_stop_view),
    path("admin/email/bulk/batches/<uuid:pk>/resume/", bulk_email_views.bulk_batch_resume_view),
]
